### PR TITLE
fix: typos in documentation files

### PR DESCRIPTION
**Pull request by vtjl10**
This pull request contains changes to improve clarity, correctness and structure.

**Description correction:**
Corrected "validateer" to "validator".
Corrected "set up the the Integritee" to "set up the Integritee".
Corrected "degratation" to "degradation".
Corrected "imortant" to "important".

Please review the changes and let me know if any additional changes are needed.

### CODE REVIEW

**Comment by vtjl10** [comment]
@mosonyi Hi! Apologies for the inconvenience. I just wanted to check if there’s anything I can improve in my pull request. Please feel free to ask any questions or let me know if any changes are needed to meet the project's merge requirements. I’m happy to make adjustments!

**Comment by vtjl10** [comment]
@brenzi Hi! Apologies for the inconvenience. I just wanted to check if there’s anything I can improve in my pull request. Please feel free to ask any questions or let me know if any changes are needed to meet the project's merge requirements. I’m happy to make adjustments!

**Comment by Giulio2002** [comment]
this guy is an airdrop farmer

**Review by brenzi — COMMENTED** [review]
Validateer is a deliberate wordplay

**Pull request closed without merging**
